import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import StyleDictionary from "style-dictionary";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputDirectory = process.env.SCHOLENS_TOKEN_OUTPUT_DIR
  ? path.resolve(process.env.SCHOLENS_TOKEN_OUTPUT_DIR)
  : path.join(root, "src/design-system/generated");
const tokenDirectory = path.join(root, "src/design-system/tokens");

const formatValue = (value) => {
  if (
    typeof value === "object" &&
    value &&
    "value" in value &&
    "unit" in value
  ) {
    return `${value.value}${value.unit}`;
  }
  return String(value);
};

StyleDictionary.registerFormat({
  name: "scholens/css-variables",
  format: ({ dictionary, options }) => {
    const lines = dictionary.allTokens
      .filter((token) => options.prefixes.includes(token.path[0]))
      .map(
        (token) =>
          `  --${token.path.join("-")}: ${formatValue(token.$value ?? token.value)};`,
      )
      .sort();

    return `${options.selector} {\n${lines.join("\n")}\n}\n`;
  },
});

const build = async ({ name, sources, selector, prefixes }) => {
  const dictionary = new StyleDictionary({
    source: sources.map((source) => path.join(tokenDirectory, source)),
    platforms: {
      css: {
        transformGroup: "css",
        buildPath: `${outputDirectory}/`,
        files: [
          {
            destination: `${name}.css`,
            format: "scholens/css-variables",
            options: { selector, prefixes },
          },
        ],
      },
    },
  });

  await dictionary.buildAllPlatforms();
};

await fs.mkdir(outputDirectory, { recursive: true });

await build({
  name: "dimensions",
  sources: ["dimensions.json"],
  selector: ":root",
  prefixes: [
    "space",
    "radius",
    "layout",
    "control",
    "icon",
    "touch",
    "border",
    "focus",
    "opacity",
  ],
});

for (const appearance of ["light", "dark"]) {
  await build({
    name: `colors-${appearance}`,
    sources: [
      "primitives.json",
      "themes/default.json",
      `semantic/${appearance}.json`,
    ],
    selector: `[data-theme=\"default\"][data-color-scheme=\"${appearance}\"]`,
    prefixes: ["color"],
  });
}

const metadata =
  `// Generated by scripts/build-tokens.mjs. Do not edit.\n` +
  `export const themeNames = [\"default\"] as const;\n` +
  `export const colorSchemes = [\"light\", \"dark\"] as const;\n` +
  `export const colorSchemePreferences = [\"system\", ...colorSchemes] as const;\n\n` +
  `export type ThemeName = (typeof themeNames)[number];\n` +
  `export type ColorScheme = (typeof colorSchemes)[number];\n` +
  `export type ColorSchemePreference = (typeof colorSchemePreferences)[number];\n`;

await fs.writeFile(path.join(outputDirectory, "theme-metadata.ts"), metadata);
