"""Typed SQLAlchemy model registry for the Scholens product schema."""

from .base import Base, JsonScalar, JsonValue
from .enums import (
    ArtifactKind,
    ConversableType,
    DocumentProcessingStatus,
    HighlightType,
    JobStatus,
    PaperStatus,
    ReasoningLevel,
    RoleType,
    SubscriptionPlan,
    SubscriptionStatus,
    StripeWebhookEventStatus,
    ZoteroImportSource,
    ZoteroImportStatus,
)
from .identity import AuthUser, UserProfile
from .integrations import ZoteroConnection, ZoteroImportedItem, ZoteroOAuthPending
from .content import (
    Annotation,
    Artifact,
    AudioOverview,
    AudioOverviewJob,
    Conversation,
    Highlight,
    JobsWebhookNonce,
    LibraryPaper,
    LibraryPaperTag,
    Message,
    Document,
    PaperImage,
    PaperPassage,
    PaperTag,
    PaperUploadJob,
    TokenUsageEvent,
    TokenWeeklyUsage,
)
from .projects import Project, ProjectCollaborator, ProjectInvitation, ProjectPaper
from .commerce import (
    DataTableExtractionJob,
    DataTableExtractionResult,
    DataTableRow,
    Onboarding,
    StripeWebhookEvent,
    Subscription,
)

__all__ = [
    "Annotation",
    "Artifact",
    "ArtifactKind",
    "AudioOverview",
    "AudioOverviewJob",
    "AuthUser",
    "Base",
    "ConversableType",
    "DocumentProcessingStatus",
    "Conversation",
    "DataTableExtractionJob",
    "DataTableExtractionResult",
    "DataTableRow",
    "Highlight",
    "HighlightType",
    "JobStatus",
    "JobsWebhookNonce",
    "LibraryPaper",
    "LibraryPaperTag",
    "JsonScalar",
    "JsonValue",
    "Message",
    "Onboarding",
    "Document",
    "PaperImage",
    "PaperPassage",
    "PaperStatus",
    "PaperTag",
    "PaperUploadJob",
    "Project",
    "ProjectCollaborator",
    "ProjectInvitation",
    "ProjectPaper",
    "ReasoningLevel",
    "RoleType",
    "Subscription",
    "SubscriptionPlan",
    "SubscriptionStatus",
    "StripeWebhookEvent",
    "StripeWebhookEventStatus",
    "TokenUsageEvent",
    "TokenWeeklyUsage",
    "UserProfile",
    "ZoteroConnection",
    "ZoteroImportSource",
    "ZoteroImportStatus",
    "ZoteroImportedItem",
    "ZoteroOAuthPending",
]
