"""Create the complete Scholens product schema.

Revision ID: 59636e6aa2f2
Revises:
Create Date: 2026-07-23 03:38:19.539316+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "59636e6aa2f2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs_webhook_nonces",
        sa.Column("nonce", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("nonce"),
        schema="scholens",
    )
    op.create_table(
        "stripe_webhook_events",
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('processing', 'completed', 'failed', 'ignored')",
            name="ck_stripe_webhook_events_status",
        ),
        sa.PrimaryKeyConstraint("event_id"),
        schema="scholens",
    )
    op.create_table(
        "token_weekly_usage",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("used_tokens", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "week_start"),
        schema="scholens",
    )
    op.create_table(
        "token_usage_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("operation_id", sa.String(length=128), nullable=False),
        sa.Column("feature", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("reasoning_level", sa.String(length=16), nullable=False),
        sa.Column("provider_request_id", sa.String(length=160), nullable=True),
        sa.Column("prompt_tokens", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "completion_tokens", sa.BigInteger(), server_default="0", nullable=False
        ),
        sa.Column(
            "reasoning_tokens", sa.BigInteger(), server_default="0", nullable=False
        ),
        sa.Column(
            "cache_hit_tokens", sa.BigInteger(), server_default="0", nullable=False
        ),
        sa.Column(
            "cache_miss_tokens", sa.BigInteger(), server_default="0", nullable=False
        ),
        sa.Column("total_tokens", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_token_usage_idempotency_key"),
        schema="scholens",
    )
    op.create_index(
        "ix_token_usage_user_week",
        "token_usage_events",
        ["user_id", "week_start"],
        schema="scholens",
    )
    op.create_table(
        "audio_overview_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("conversable_id", sa.UUID(), nullable=False),
        sa.Column("conversable_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("status_message", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(conversable_type = 'paper' AND conversable_id IS NOT NULL) OR (conversable_type = 'project' AND conversable_id IS NOT NULL) OR (conversable_type = 'everything' AND conversable_id IS NULL)",
            name="check_audio_overview_job_conversable_consistency",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "audio_overviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("s3_object_key", sa.String(), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("conversable_id", sa.UUID(), nullable=False),
        sa.Column("conversable_type", sa.String(), nullable=False),
        sa.Column(
            "is_shared",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(conversable_type = 'paper' AND conversable_id IS NOT NULL) OR (conversable_type = 'project' AND conversable_id IS NOT NULL) OR (conversable_type = 'everything' AND conversable_id IS NULL)",
            name="check_audio_overview_conversable_consistency",
        ),
        sa.CheckConstraint(
            "NOT is_shared OR conversable_type = 'project'",
            name="ck_audio_overviews_shared_project",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("conversable_id", sa.UUID(), nullable=True),
        sa.Column("conversable_type", sa.String(), nullable=False),
        sa.Column("scope_label_snapshot", sa.String(length=240), nullable=True),
        sa.Column("pinned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(conversable_type = 'paper' AND conversable_id IS NOT NULL) OR (conversable_type = 'project' AND conversable_id IS NOT NULL) OR (conversable_type = 'everything' AND conversable_id IS NULL)",
            name="check_conversable_consistency",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        "ix_conversations_user_archive_activity",
        "conversations",
        ["user_id", "archived_at", "updated_at"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_conversations_user_pinned",
        "conversations",
        ["user_id", "pinned_at"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "onboarding",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("research_fields", sa.String(), nullable=True),
        sa.Column("research_fields_other", sa.String(), nullable=True),
        sa.Column("job_titles", sa.String(), nullable=True),
        sa.Column("job_titles_other", sa.String(), nullable=True),
        sa.Column("reading_frequency", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "paper_tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "paper_upload_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("quota_owner_id", sa.BigInteger(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column(
            "reserved_size_kb",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column("original_filename", sa.String(length=512), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("task_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reserved_size_kb >= 0",
            name="ck_paper_upload_jobs_reserved_size_nonnegative",
        ),
        sa.ForeignKeyConstraint(
            ["quota_owner_id"],
            ["auth.users.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["auth.users.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_projects_owner_id"),
        "projects",
        ["owner_id"],
        unique=False,
        schema="scholens",
    )
    op.create_foreign_key(
        "fk_paper_upload_jobs_project_id_projects",
        "paper_upload_jobs",
        "projects",
        ["project_id"],
        ["id"],
        source_schema="scholens",
        referent_schema="scholens",
        ondelete="SET NULL",
    )
    op.create_index(
        "ix_paper_upload_jobs_project_status",
        "paper_upload_jobs",
        ["project_id", "status"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_paper_upload_jobs_quota_status",
        "paper_upload_jobs",
        ["quota_owner_id", "status"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("plan", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(), nullable=True),
        sa.Column("stripe_price_id", sa.String(), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=True),
        sa.Column("stripe_schedule_id", sa.String(), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        schema="scholens",
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("locale", sa.String(), nullable=True),
        sa.Column(
            "is_admin",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_blocked",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        schema="scholens",
    )
    op.create_table(
        "zotero_connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("zotero_user_id", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        schema="scholens",
    )
    op.create_table(
        "zotero_oauth_pending",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("oauth_token", sa.String(), nullable=False),
        sa.Column("oauth_token_secret", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_zotero_oauth_pending_oauth_token"),
        "zotero_oauth_pending",
        ["oauth_token"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "data_table_extraction_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("columns", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("task_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "is_shared",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="CASCADE"
        ),
        sa.CheckConstraint(
            "NOT is_shared OR project_id IS NOT NULL",
            name="ck_data_table_jobs_shared_project",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("references", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trace", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["scholens.conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_url", sa.String(), nullable=False),
        sa.Column("preview_url", sa.String(), nullable=True),
        sa.Column("s3_object_key", sa.String(), nullable=True),
        sa.Column("authors", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("institutions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("keywords", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "summary_citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("publish_date", sa.DateTime(), nullable=True),
        sa.Column("starter_questions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("parser_markdown_s3_key", sa.String(), nullable=True),
        sa.Column("parser_archive_s3_key", sa.String(), nullable=True),
        sa.Column("parser_backend", sa.String(), nullable=True),
        sa.Column("parser_quality", sa.String(), nullable=True),
        sa.Column("parser_version", sa.String(), nullable=True),
        sa.Column("parser_warning_code", sa.String(), nullable=True),
        sa.Column("ts_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column(
            "page_offset_map", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("upload_job_id", sa.UUID(), nullable=True),
        sa.Column("cached_presigned_url", sa.String(), nullable=True),
        sa.Column(
            "presigned_url_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("journal", sa.String(), nullable=True),
        sa.Column("publisher", sa.String(), nullable=True),
        sa.Column("attempted_metadata_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "field_provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("size_in_kb", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "parser_backend IS NULL OR parser_backend IN ('mineru', 'pymupdf')",
            name="ck_documents_parser_backend",
        ),
        sa.CheckConstraint(
            "parser_quality IS NULL OR parser_quality IN ('full', 'text_only')",
            name="ck_documents_parser_quality",
        ),
        sa.ForeignKeyConstraint(
            ["upload_job_id"], ["scholens.paper_upload_jobs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["auth.users.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_documents_created_by_id"),
        "documents",
        ["created_by_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_documents_ts_vector",
        "documents",
        ["ts_vector"],
        unique=False,
        schema="scholens",
        postgresql_using="gin",
    )
    op.create_table(
        "library_papers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.String(),
            server_default="reading",
            nullable=False,
        ),
        sa.Column(
            "last_accessed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "is_public",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("share_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["scholens.documents.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "document_id",
            name="uq_library_papers_user_document",
        ),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_library_papers_document_id"),
        "library_papers",
        ["document_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_library_papers_share_id"),
        "library_papers",
        ["share_id"],
        unique=True,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_library_papers_user_id"),
        "library_papers",
        ["user_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_library_papers_user_activity",
        "library_papers",
        ["user_id", "updated_at"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "project_collaborators",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "can_edit_project",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "can_manage_papers",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "can_manage_collaborators",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "user_id",
            name="uq_project_collaborator_project_user",
        ),
        schema="scholens",
    )
    op.create_index(
        "ix_project_collaborators_user_id",
        "project_collaborators",
        ["user_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "project_invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("invited_by_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "can_edit_project",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "can_manage_papers",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "can_manage_collaborators",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_id"],
            ["auth.users.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        "ix_project_invitations_project_email",
        "project_invitations",
        ["project_id", "email"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_project_invitations_token_hash",
        "project_invitations",
        ["token_hash"],
        unique=True,
        schema="scholens",
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("scope_type", sa.String(), nullable=False),
        sa.Column("scope_id", sa.UUID(), nullable=True),
        sa.Column(
            "is_shared",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["scholens.messages.id"], ondelete="SET NULL"
        ),
        sa.CheckConstraint(
            "NOT is_shared OR scope_type = 'project'",
            name="ck_artifacts_shared_project_scope",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        "ix_artifacts_message_id",
        "artifacts",
        ["message_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_artifacts_scope",
        "artifacts",
        ["scope_type", "scope_id", "kind", "created_at"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_artifacts_user_id"),
        "artifacts",
        ["user_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "data_table_extraction_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("columns", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("row_failures", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["scholens.data_table_extraction_jobs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
        schema="scholens",
    )
    op.create_table(
        "highlights",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("position", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("zotero_annotation_key", sa.String(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column(
            "is_shared",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="CASCADE"
        ),
        sa.CheckConstraint(
            "NOT is_shared OR project_id IS NOT NULL",
            name="ck_highlights_shared_project",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        "uq_highlight_paper_zotero_annotation_key",
        "highlights",
        ["paper_id", "zotero_annotation_key", "user_id"],
        unique=True,
        schema="scholens",
        postgresql_where=sa.text("zotero_annotation_key IS NOT NULL"),
    )
    op.create_index(
        "ix_highlights_project_visibility",
        "highlights",
        ["project_id", "is_shared", "created_at"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_highlights_project_id"),
        "highlights",
        ["project_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_highlights_user_id"),
        "highlights",
        ["user_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "paper_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("s3_object_key", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("image_index", sa.Integer(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("placeholder_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "paper_notes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column(
            "is_shared",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="CASCADE"
        ),
        sa.CheckConstraint(
            "NOT is_shared OR project_id IS NOT NULL",
            name="ck_paper_notes_shared_project",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_paper_notes_project_id"),
        "paper_notes",
        ["project_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_paper_notes_user_id"),
        "paper_notes",
        ["user_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "uq_paper_notes_private_owner",
        "paper_notes",
        ["paper_id", "user_id"],
        unique=True,
        schema="scholens",
        postgresql_where=sa.text("project_id IS NULL"),
    )
    op.create_index(
        "uq_paper_notes_project_owner",
        "paper_notes",
        ["paper_id", "project_id", "user_id"],
        unique=True,
        schema="scholens",
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.create_table(
        "paper_passages",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("ts_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paper_id", "start_line"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_paper_passages_paper_id"),
        "paper_passages",
        ["paper_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_paper_passages_ts_vector",
        "paper_passages",
        ["ts_vector"],
        unique=False,
        schema="scholens",
        postgresql_using="gin",
    )
    op.create_table(
        "library_paper_tags",
        sa.Column("library_paper_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["library_paper_id"],
            ["scholens.library_papers.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["scholens.paper_tags.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("library_paper_id", "tag_id"),
        schema="scholens",
    )
    op.create_table(
        "project_papers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("added_by_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["scholens.documents.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["added_by_id"], ["auth.users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "document_id",
            name="uq_project_papers_project_document",
        ),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_project_papers_document_id"),
        "project_papers",
        ["document_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_project_papers_project_id"),
        "project_papers",
        ["project_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "zotero_imported_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("zotero_item_key", sa.String(), nullable=False),
        sa.Column("zotero_attachment_key", sa.String(), nullable=True),
        sa.Column("import_source", sa.String(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("paper_id", sa.UUID(), nullable=True),
        sa.Column("upload_job_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "annotations_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.documents.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["upload_job_id"], ["scholens.paper_upload_jobs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "zotero_item_key", name="uq_zotero_import_user_item"
        ),
        schema="scholens",
    )
    op.create_table(
        "annotations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("highlight_id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["highlight_id"],
            ["scholens.highlights.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "data_table_rows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("data_table_id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["data_table_id"],
            ["scholens.data_table_extraction_results.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        "ix_data_table_rows_data_table_id",
        "data_table_rows",
        ["data_table_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_data_table_rows_paper_id",
        "data_table_rows",
        ["paper_id"],
        unique=False,
        schema="scholens",
    )
    op.execute(
        """
        CREATE FUNCTION scholens.document_content_trigger() RETURNS trigger AS $$
        BEGIN
            NEW.ts_vector :=
                setweight(
                    to_tsvector('pg_catalog.english', coalesce(NEW.title, '')),
                    'A'
                ) ||
                setweight(
                    to_tsvector('pg_catalog.english', coalesce(NEW.raw_content, '')),
                    'D'
                );
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER tsvectorupdate
            BEFORE INSERT OR UPDATE ON scholens.documents
            FOR EACH ROW
            EXECUTE FUNCTION scholens.document_content_trigger()
        """
    )
    op.execute(
        """
        CREATE FUNCTION scholens.paper_passages_tsvector_trigger()
        RETURNS trigger AS $$
        BEGIN
            NEW.ts_vector :=
                to_tsvector('pg_catalog.english', coalesce(NEW.content, ''));
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER paper_passages_tsvectorupdate
            BEFORE INSERT OR UPDATE ON scholens.paper_passages
            FOR EACH ROW
            EXECUTE FUNCTION scholens.paper_passages_tsvector_trigger()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_token_usage_user_week",
        table_name="token_usage_events",
        schema="scholens",
    )
    op.drop_table("token_usage_events", schema="scholens")
    op.drop_table("token_weekly_usage", schema="scholens")
    op.drop_table("stripe_webhook_events", schema="scholens")
    op.drop_table("jobs_webhook_nonces", schema="scholens")
    op.execute(
        "DROP TRIGGER IF EXISTS paper_passages_tsvectorupdate "
        "ON scholens.paper_passages"
    )
    op.execute("DROP FUNCTION IF EXISTS scholens.paper_passages_tsvector_trigger()")
    op.execute("DROP TRIGGER IF EXISTS tsvectorupdate ON scholens.documents")
    op.execute("DROP FUNCTION IF EXISTS scholens.document_content_trigger()")
    op.drop_index(
        "ix_data_table_rows_paper_id", table_name="data_table_rows", schema="scholens"
    )
    op.drop_index(
        "ix_data_table_rows_data_table_id",
        table_name="data_table_rows",
        schema="scholens",
    )
    op.drop_table("data_table_rows", schema="scholens")
    op.drop_table("annotations", schema="scholens")
    op.drop_table("zotero_imported_items", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_project_papers_project_id"),
        table_name="project_papers",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_project_papers_document_id"),
        table_name="project_papers",
        schema="scholens",
    )
    op.drop_table("project_papers", schema="scholens")
    op.drop_table("library_paper_tags", schema="scholens")
    op.drop_index(
        "ix_paper_passages_ts_vector",
        table_name="paper_passages",
        schema="scholens",
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_scholens_paper_passages_paper_id"),
        table_name="paper_passages",
        schema="scholens",
    )
    op.drop_table("paper_passages", schema="scholens")
    op.drop_index(
        "uq_paper_notes_project_owner",
        table_name="paper_notes",
        schema="scholens",
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_paper_notes_private_owner",
        table_name="paper_notes",
        schema="scholens",
        postgresql_where=sa.text("project_id IS NULL"),
    )
    op.drop_index(
        op.f("ix_scholens_paper_notes_user_id"),
        table_name="paper_notes",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_paper_notes_project_id"),
        table_name="paper_notes",
        schema="scholens",
    )
    op.drop_table("paper_notes", schema="scholens")
    op.drop_table("paper_images", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_highlights_user_id"),
        table_name="highlights",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_highlights_project_id"),
        table_name="highlights",
        schema="scholens",
    )
    op.drop_index(
        "ix_highlights_project_visibility",
        table_name="highlights",
        schema="scholens",
    )
    op.drop_index(
        "uq_highlight_paper_zotero_annotation_key",
        table_name="highlights",
        schema="scholens",
        postgresql_where=sa.text("zotero_annotation_key IS NOT NULL"),
    )
    op.drop_table("highlights", schema="scholens")
    op.drop_table("data_table_extraction_results", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_artifacts_user_id"),
        table_name="artifacts",
        schema="scholens",
    )
    op.drop_index("ix_artifacts_scope", table_name="artifacts", schema="scholens")
    op.drop_index("ix_artifacts_message_id", table_name="artifacts", schema="scholens")
    op.drop_table("artifacts", schema="scholens")
    op.drop_index(
        "ix_project_invitations_token_hash",
        table_name="project_invitations",
        schema="scholens",
    )
    op.drop_index(
        "ix_project_invitations_project_email",
        table_name="project_invitations",
        schema="scholens",
    )
    op.drop_table("project_invitations", schema="scholens")
    op.drop_index(
        "ix_project_collaborators_user_id",
        table_name="project_collaborators",
        schema="scholens",
    )
    op.drop_table("project_collaborators", schema="scholens")
    op.drop_index(
        "ix_documents_ts_vector",
        table_name="documents",
        schema="scholens",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_library_papers_user_activity",
        table_name="library_papers",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_library_papers_user_id"),
        table_name="library_papers",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_library_papers_share_id"),
        table_name="library_papers",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_library_papers_document_id"),
        table_name="library_papers",
        schema="scholens",
    )
    op.drop_table("library_papers", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_documents_created_by_id"),
        table_name="documents",
        schema="scholens",
    )
    op.drop_table("documents", schema="scholens")
    op.drop_table("messages", schema="scholens")
    op.drop_table("data_table_extraction_jobs", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_zotero_oauth_pending_oauth_token"),
        table_name="zotero_oauth_pending",
        schema="scholens",
    )
    op.drop_table("zotero_oauth_pending", schema="scholens")
    op.drop_table("zotero_connections", schema="scholens")
    op.drop_table("user_profiles", schema="scholens")
    op.drop_table("subscriptions", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_projects_owner_id"),
        table_name="projects",
        schema="scholens",
    )
    op.drop_index(
        "ix_paper_upload_jobs_quota_status",
        table_name="paper_upload_jobs",
        schema="scholens",
    )
    op.drop_index(
        "ix_paper_upload_jobs_project_status",
        table_name="paper_upload_jobs",
        schema="scholens",
    )
    op.drop_constraint(
        "fk_paper_upload_jobs_project_id_projects",
        "paper_upload_jobs",
        schema="scholens",
        type_="foreignkey",
    )
    op.drop_table("projects", schema="scholens")
    op.drop_table("paper_upload_jobs", schema="scholens")
    op.drop_table("paper_tags", schema="scholens")
    op.drop_table("onboarding", schema="scholens")
    op.drop_index(
        "ix_conversations_user_pinned",
        table_name="conversations",
        schema="scholens",
    )
    op.drop_index(
        "ix_conversations_user_archive_activity",
        table_name="conversations",
        schema="scholens",
    )
    op.drop_table("conversations", schema="scholens")
    op.drop_table("audio_overviews", schema="scholens")
    op.drop_table("audio_overview_jobs", schema="scholens")
    # ### end Alembic commands ###
