"""scholens initial

Revision ID: a21f80661812
Revises:
Create Date: 2026-07-28 10:30:25.961708+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a21f80661812"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs_webhook_nonces",
        sa.Column("nonce", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("nonce"),
        schema="scholens",
    )
    op.create_table(
        "stripe_webhook_events",
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('processing', 'completed', 'failed', 'ignored')",
            name="ck_stripe_webhook_events_status",
        ),
        sa.PrimaryKeyConstraint("event_id"),
        schema="scholens",
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("s3_object_key", sa.String(length=1024), nullable=False),
        sa.Column("preview_s3_key", sa.String(length=1024), nullable=True),
        sa.Column("authors", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("institutions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("keywords", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "summary_citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("publish_date", sa.DateTime(), nullable=True),
        sa.Column("starter_questions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("parser_markdown_s3_key", sa.String(), nullable=True),
        sa.Column("parser_archive_s3_key", sa.String(), nullable=True),
        sa.Column("parser_backend", sa.String(), nullable=True),
        sa.Column("parser_quality", sa.String(), nullable=True),
        sa.Column("parser_version", sa.String(), nullable=True),
        sa.Column("parser_warning_code", sa.String(), nullable=True),
        sa.Column(
            "processing_status",
            sa.String(length=16),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("processing_job_id", sa.UUID(), nullable=True),
        sa.Column("gc_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ts_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column(
            "page_offset_map", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("journal", sa.String(), nullable=True),
        sa.Column("publisher", sa.String(), nullable=True),
        sa.Column("attempted_metadata_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "field_provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "parser_backend IS NULL OR parser_backend IN ('mineru', 'pymupdf')",
            name="ck_documents_parser_backend",
        ),
        sa.CheckConstraint(
            "parser_quality IS NULL OR parser_quality IN ('full', 'text_only')",
            name="ck_documents_parser_quality",
        ),
        sa.CheckConstraint(
            "processing_status IN ('pending', 'processing', 'completed', 'failed')",
            name="ck_documents_processing_status",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["auth.users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256", name="uq_documents_sha256"),
        schema="scholens",
    )
    op.create_index(
        "ix_documents_ts_vector",
        "documents",
        ["ts_vector"],
        unique=False,
        schema="scholens",
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_scholens_documents_created_by_id"),
        "documents",
        ["created_by_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_documents_gc_after"),
        "documents",
        ["gc_after"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "onboarding",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("research_fields", sa.String(), nullable=True),
        sa.Column("research_fields_other", sa.String(), nullable=True),
        sa.Column("job_titles", sa.String(), nullable=True),
        sa.Column("job_titles_other", sa.String(), nullable=True),
        sa.Column("reading_frequency", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "paper_tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["auth.users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_projects_owner_id"),
        "projects",
        ["owner_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("plan", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(), nullable=True),
        sa.Column("stripe_price_id", sa.String(), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=True),
        sa.Column("stripe_schedule_id", sa.String(), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        schema="scholens",
    )
    op.create_table(
        "token_usage_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("operation_id", sa.String(length=128), nullable=False),
        sa.Column("feature", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("reasoning_level", sa.String(length=16), nullable=False),
        sa.Column("provider_request_id", sa.String(length=160), nullable=True),
        sa.Column("prompt_tokens", sa.BigInteger(), nullable=False),
        sa.Column("completion_tokens", sa.BigInteger(), nullable=False),
        sa.Column("reasoning_tokens", sa.BigInteger(), nullable=False),
        sa.Column("cache_hit_tokens", sa.BigInteger(), nullable=False),
        sa.Column("cache_miss_tokens", sa.BigInteger(), nullable=False),
        sa.Column("total_tokens", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_token_usage_idempotency_key"),
        schema="scholens",
    )
    op.create_index(
        "ix_token_usage_user_week",
        "token_usage_events",
        ["user_id", "week_start"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "token_weekly_usage",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("used_tokens", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "week_start"),
        schema="scholens",
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("locale", sa.String(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_blocked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        schema="scholens",
    )
    op.create_table(
        "zotero_connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("zotero_user_id", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        schema="scholens",
    )
    op.create_table(
        "zotero_oauth_pending",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("oauth_token", sa.String(), nullable=False),
        sa.Column("oauth_token_secret", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_zotero_oauth_pending_oauth_token"),
        "zotero_oauth_pending",
        ["oauth_token"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("scope_label_snapshot", sa.String(length=240), nullable=True),
        sa.Column("context_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pinned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope_type = 'global' AND project_id IS NULL AND document_id IS NULL AND context_deleted_at IS NULL) OR (scope_type = 'project' AND document_id IS NULL AND ((project_id IS NOT NULL AND context_deleted_at IS NULL) OR (project_id IS NULL AND context_deleted_at IS NOT NULL))) OR (scope_type = 'paper' AND project_id IS NULL AND ((document_id IS NOT NULL AND context_deleted_at IS NULL) OR (document_id IS NULL AND context_deleted_at IS NOT NULL)))",
            name="ck_conversations_scope_consistency",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["scholens.documents.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        "ix_conversations_user_archive_activity",
        "conversations",
        ["user_id", "archived_at", "updated_at"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_conversations_user_pinned",
        "conversations",
        ["user_id", "pinned_at"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_conversations_document_id"),
        "conversations",
        ["document_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_conversations_project_id"),
        "conversations",
        ["project_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("operation", sa.String(length=40), nullable=False),
        sa.Column("requested_by_id", sa.BigInteger(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default="pending", nullable=False
        ),
        sa.Column("progress_message", sa.String(length=240), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed', 'cancelled')",
            name="ck_jobs_status",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["scholens.documents.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"], ["auth.users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_jobs_idempotency_key"),
        schema="scholens",
    )
    op.create_index(
        "ix_jobs_document_status",
        "jobs",
        ["document_id", "status"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_jobs_project_status",
        "jobs",
        ["project_id", "status"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_jobs_requester_activity",
        "jobs",
        ["requested_by_id", "created_at"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "library_papers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), server_default="reading", nullable=False),
        sa.Column(
            "last_accessed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_public", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("share_token_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "metadata_overrides",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["scholens.documents.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "document_id", name="uq_library_papers_user_document"
        ),
        schema="scholens",
    )
    op.create_index(
        "ix_library_papers_user_activity",
        "library_papers",
        ["user_id", "updated_at"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_library_papers_document_id"),
        "library_papers",
        ["document_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_library_papers_share_token_hash"),
        "library_papers",
        ["share_token_hash"],
        unique=True,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_library_papers_user_id"),
        "library_papers",
        ["user_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "paper_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("s3_object_key", sa.String(), nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("image_index", sa.Integer(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("placeholder_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "paper_passages",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("ts_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paper_id", "start_line"),
        schema="scholens",
    )
    op.create_index(
        "ix_paper_passages_ts_vector",
        "paper_passages",
        ["ts_vector"],
        unique=False,
        schema="scholens",
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_scholens_paper_passages_paper_id"),
        "paper_passages",
        ["paper_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "project_collaborators",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "can_edit_project", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "can_manage_papers", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "can_manage_collaborators",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "user_id", name="uq_project_collaborator_project_user"
        ),
        schema="scholens",
    )
    op.create_index(
        "ix_project_collaborators_user_id",
        "project_collaborators",
        ["user_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "project_invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("invited_by_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "can_edit_project", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "can_manage_papers", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "can_manage_collaborators",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_id"], ["auth.users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        "ix_project_invitations_project_email",
        "project_invitations",
        ["project_id", "email"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_project_invitations_token_hash",
        "project_invitations",
        ["token_hash"],
        unique=True,
        schema="scholens",
    )
    op.create_index(
        "uq_project_invitations_pending_project_email",
        "project_invitations",
        ["project_id", "email"],
        unique=True,
        schema="scholens",
        postgresql_where=sa.text("accepted_at IS NULL AND revoked_at IS NULL"),
    )
    op.create_table(
        "project_papers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("added_by_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["added_by_id"], ["auth.users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["scholens.documents.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "document_id", name="uq_project_papers_project_document"
        ),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_project_papers_document_id"),
        "project_papers",
        ["document_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_project_papers_project_id"),
        "project_papers",
        ["project_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "job_dispatches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("task_name", sa.String(length=120), nullable=False),
        sa.Column("queue", sa.String(length=80), nullable=False),
        sa.Column("kwargs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default="pending", nullable=False
        ),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=80), nullable=True),
        sa.Column("last_error_detail", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'published')", name="ck_job_dispatches_status"
        ),
        sa.ForeignKeyConstraint(["job_id"], ["scholens.jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
        schema="scholens",
    )
    op.create_index(
        "ix_job_dispatches_pending",
        "job_dispatches",
        ["status", "available_at", "created_at"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "library_paper_tags",
        sa.Column("library_paper_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["library_paper_id"], ["scholens.library_papers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["scholens.paper_tags.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("library_paper_id", "tag_id"),
        schema="scholens",
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("references", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trace", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["scholens.conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "conversation_id", "sequence", name="uq_messages_conversation_sequence"
        ),
        schema="scholens",
    )
    op.create_table(
        "upload_reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("quota_owner_id", sa.BigInteger(), nullable=False),
        sa.Column("reserved_size_kb", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "reserved_reference_count", sa.Integer(), server_default="1", nullable=False
        ),
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "reference_created", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("original_filename", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reserved_reference_count IN (0, 1)",
            name="ck_upload_reservations_reserved_reference_count",
        ),
        sa.CheckConstraint(
            "reserved_size_kb >= 0",
            name="ck_upload_reservations_reserved_size_nonnegative",
        ),
        sa.ForeignKeyConstraint(["id"], ["scholens.jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["quota_owner_id"], ["auth.users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_upload_reservations_content_sha256"),
        "upload_reservations",
        ["content_sha256"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_upload_reservations_quota_owner",
        "upload_reservations",
        ["quota_owner_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "research_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("is_shared", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("source_message_id", sa.UUID(), nullable=True),
        sa.Column("source_job_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope_type = 'personal' AND document_id IS NULL AND project_id IS NULL) OR (scope_type = 'document' AND document_id IS NOT NULL AND project_id IS NULL) OR (scope_type = 'project' AND project_id IS NOT NULL AND document_id IS NULL)",
            name="ck_research_items_scope_consistency",
        ),
        sa.CheckConstraint(
            "kind != 'highlight_thread' OR scope_type = 'document'",
            name="ck_research_items_highlight_document_scope",
        ),
        sa.CheckConstraint(
            "scope_type != 'personal' OR NOT is_shared",
            name="ck_research_items_personal_private",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["auth.users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["scholens.documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_job_id"], ["scholens.jobs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"], ["scholens.messages.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_job_id"),
        schema="scholens",
    )
    op.create_index(
        "ix_research_items_creator_activity",
        "research_items",
        ["created_by_id", "created_at"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_research_items_document_visibility",
        "research_items",
        ["document_id", "is_shared", "created_at"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_research_items_project_visibility",
        "research_items",
        ["project_id", "is_shared", "created_at"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "zotero_imported_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("zotero_item_key", sa.String(), nullable=False),
        sa.Column("zotero_attachment_key", sa.String(), nullable=True),
        sa.Column("import_source", sa.String(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("paper_id", sa.UUID(), nullable=True),
        sa.Column("upload_job_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "annotations_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.documents.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["upload_job_id"], ["scholens.upload_reservations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "zotero_item_key", name="uq_zotero_import_user_item"
        ),
        schema="scholens",
    )
    op.create_table(
        "citation_outputs",
        sa.Column("research_item_id", sa.UUID(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["research_item_id"], ["scholens.research_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("research_item_id"),
        schema="scholens",
    )
    op.create_table(
        "highlight_threads",
        sa.Column("research_item_id", sa.UUID(), nullable=False),
        sa.Column("quote_text", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("position", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("color", sa.String(length=32), server_default="blue", nullable=False),
        sa.Column("role", sa.String(length=16), server_default="user", nullable=False),
        sa.Column("zotero_annotation_key", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["research_item_id"], ["scholens.research_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("research_item_id"),
        schema="scholens",
    )
    op.create_table(
        "research_audio_overviews",
        sa.Column("research_item_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column(
            "citations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("s3_object_key", sa.String(length=1024), nullable=False),
        sa.Column("voice_id", sa.String(length=160), nullable=False),
        sa.Column("model_version", sa.String(length=160), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["research_item_id"], ["scholens.research_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("research_item_id"),
        schema="scholens",
    )
    op.create_table(
        "research_data_tables",
        sa.Column("research_item_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=True),
        sa.Column("columns", sa.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "rows",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "citations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "row_failures",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["research_item_id"], ["scholens.research_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("research_item_id"),
        schema="scholens",
    )
    op.create_table(
        "annotation_comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=16), server_default="user", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["auth.users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["scholens.highlight_threads.research_item_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        "ix_annotation_comments_thread",
        "annotation_comments",
        ["thread_id", "created_at"],
        unique=False,
        schema="scholens",
    )
    op.execute(
        """
        CREATE FUNCTION scholens.document_content_trigger() RETURNS trigger AS $$
        BEGIN
            NEW.ts_vector :=
                setweight(
                    to_tsvector('pg_catalog.english', coalesce(NEW.title, '')),
                    'A'
                ) ||
                setweight(
                    to_tsvector('pg_catalog.english', coalesce(NEW.raw_content, '')),
                    'D'
                );
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER tsvectorupdate
            BEFORE INSERT OR UPDATE ON scholens.documents
            FOR EACH ROW
            EXECUTE FUNCTION scholens.document_content_trigger()
        """
    )
    op.execute(
        """
        CREATE FUNCTION scholens.paper_passages_tsvector_trigger()
        RETURNS trigger AS $$
        BEGIN
            NEW.ts_vector :=
                to_tsvector('pg_catalog.english', coalesce(NEW.content, ''));
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER paper_passages_tsvectorupdate
            BEFORE INSERT OR UPDATE ON scholens.paper_passages
            FOR EACH ROW
            EXECUTE FUNCTION scholens.paper_passages_tsvector_trigger()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DROP TRIGGER IF EXISTS paper_passages_tsvectorupdate "
        "ON scholens.paper_passages"
    )
    op.execute("DROP FUNCTION IF EXISTS scholens.paper_passages_tsvector_trigger()")
    op.execute("DROP TRIGGER IF EXISTS tsvectorupdate ON scholens.documents")
    op.execute("DROP FUNCTION IF EXISTS scholens.document_content_trigger()")
    op.drop_index(
        "ix_annotation_comments_thread",
        table_name="annotation_comments",
        schema="scholens",
    )
    op.drop_table("annotation_comments", schema="scholens")
    op.drop_table("research_data_tables", schema="scholens")
    op.drop_table("research_audio_overviews", schema="scholens")
    op.drop_table("highlight_threads", schema="scholens")
    op.drop_table("citation_outputs", schema="scholens")
    op.drop_table("zotero_imported_items", schema="scholens")
    op.drop_index(
        "ix_research_items_project_visibility",
        table_name="research_items",
        schema="scholens",
    )
    op.drop_index(
        "ix_research_items_document_visibility",
        table_name="research_items",
        schema="scholens",
    )
    op.drop_index(
        "ix_research_items_creator_activity",
        table_name="research_items",
        schema="scholens",
    )
    op.drop_table("research_items", schema="scholens")
    op.drop_index(
        "ix_upload_reservations_quota_owner",
        table_name="upload_reservations",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_upload_reservations_content_sha256"),
        table_name="upload_reservations",
        schema="scholens",
    )
    op.drop_table("upload_reservations", schema="scholens")
    op.drop_table("messages", schema="scholens")
    op.drop_table("library_paper_tags", schema="scholens")
    op.drop_index(
        "ix_job_dispatches_pending", table_name="job_dispatches", schema="scholens"
    )
    op.drop_table("job_dispatches", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_project_papers_project_id"),
        table_name="project_papers",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_project_papers_document_id"),
        table_name="project_papers",
        schema="scholens",
    )
    op.drop_table("project_papers", schema="scholens")
    op.drop_index(
        "uq_project_invitations_pending_project_email",
        table_name="project_invitations",
        schema="scholens",
        postgresql_where=sa.text("accepted_at IS NULL AND revoked_at IS NULL"),
    )
    op.drop_index(
        "ix_project_invitations_token_hash",
        table_name="project_invitations",
        schema="scholens",
    )
    op.drop_index(
        "ix_project_invitations_project_email",
        table_name="project_invitations",
        schema="scholens",
    )
    op.drop_table("project_invitations", schema="scholens")
    op.drop_index(
        "ix_project_collaborators_user_id",
        table_name="project_collaborators",
        schema="scholens",
    )
    op.drop_table("project_collaborators", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_paper_passages_paper_id"),
        table_name="paper_passages",
        schema="scholens",
    )
    op.drop_index(
        "ix_paper_passages_ts_vector",
        table_name="paper_passages",
        schema="scholens",
        postgresql_using="gin",
    )
    op.drop_table("paper_passages", schema="scholens")
    op.drop_table("paper_images", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_library_papers_user_id"),
        table_name="library_papers",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_library_papers_share_token_hash"),
        table_name="library_papers",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_library_papers_document_id"),
        table_name="library_papers",
        schema="scholens",
    )
    op.drop_index(
        "ix_library_papers_user_activity",
        table_name="library_papers",
        schema="scholens",
    )
    op.drop_table("library_papers", schema="scholens")
    op.drop_index("ix_jobs_requester_activity", table_name="jobs", schema="scholens")
    op.drop_index("ix_jobs_project_status", table_name="jobs", schema="scholens")
    op.drop_index("ix_jobs_document_status", table_name="jobs", schema="scholens")
    op.drop_table("jobs", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_conversations_project_id"),
        table_name="conversations",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_conversations_document_id"),
        table_name="conversations",
        schema="scholens",
    )
    op.drop_index(
        "ix_conversations_user_pinned", table_name="conversations", schema="scholens"
    )
    op.drop_index(
        "ix_conversations_user_archive_activity",
        table_name="conversations",
        schema="scholens",
    )
    op.drop_table("conversations", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_zotero_oauth_pending_oauth_token"),
        table_name="zotero_oauth_pending",
        schema="scholens",
    )
    op.drop_table("zotero_oauth_pending", schema="scholens")
    op.drop_table("zotero_connections", schema="scholens")
    op.drop_table("user_profiles", schema="scholens")
    op.drop_table("token_weekly_usage", schema="scholens")
    op.drop_index(
        "ix_token_usage_user_week", table_name="token_usage_events", schema="scholens"
    )
    op.drop_table("token_usage_events", schema="scholens")
    op.drop_table("subscriptions", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_projects_owner_id"), table_name="projects", schema="scholens"
    )
    op.drop_table("projects", schema="scholens")
    op.drop_table("paper_tags", schema="scholens")
    op.drop_table("onboarding", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_documents_gc_after"),
        table_name="documents",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_documents_created_by_id"),
        table_name="documents",
        schema="scholens",
    )
    op.drop_index(
        "ix_documents_ts_vector",
        table_name="documents",
        schema="scholens",
        postgresql_using="gin",
    )
    op.drop_table("documents", schema="scholens")
    op.drop_table("stripe_webhook_events", schema="scholens")
    op.drop_table("jobs_webhook_nonces", schema="scholens")
    # ### end Alembic commands ###
