"""Create the complete Scholens product schema.

Revision ID: 59636e6aa2f2
Revises:
Create Date: 2026-07-23 03:38:19.539316+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "59636e6aa2f2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs_webhook_nonces",
        sa.Column("nonce", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("nonce"),
        schema="scholens",
    )
    op.create_table(
        "stripe_webhook_events",
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('processing', 'completed', 'failed', 'ignored')",
            name="ck_stripe_webhook_events_status",
        ),
        sa.PrimaryKeyConstraint("event_id"),
        schema="scholens",
    )
    op.create_table(
        "token_weekly_usage",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("used_tokens", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "week_start"),
        schema="scholens",
    )
    op.create_table(
        "token_usage_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("operation_id", sa.String(length=128), nullable=False),
        sa.Column("feature", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("reasoning_level", sa.String(length=16), nullable=False),
        sa.Column("provider_request_id", sa.String(length=160), nullable=True),
        sa.Column("prompt_tokens", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "completion_tokens", sa.BigInteger(), server_default="0", nullable=False
        ),
        sa.Column(
            "reasoning_tokens", sa.BigInteger(), server_default="0", nullable=False
        ),
        sa.Column(
            "cache_hit_tokens", sa.BigInteger(), server_default="0", nullable=False
        ),
        sa.Column(
            "cache_miss_tokens", sa.BigInteger(), server_default="0", nullable=False
        ),
        sa.Column("total_tokens", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_token_usage_idempotency_key"),
        schema="scholens",
    )
    op.create_index(
        "ix_token_usage_user_week",
        "token_usage_events",
        ["user_id", "week_start"],
        schema="scholens",
    )
    op.create_table(
        "audio_overview_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("conversable_id", sa.UUID(), nullable=False),
        sa.Column("conversable_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("status_message", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(conversable_type = 'paper' AND conversable_id IS NOT NULL) OR (conversable_type = 'project' AND conversable_id IS NOT NULL) OR (conversable_type = 'everything' AND conversable_id IS NULL)",
            name="check_audio_overview_job_conversable_consistency",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "audio_overviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("s3_object_key", sa.String(), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("conversable_id", sa.UUID(), nullable=False),
        sa.Column("conversable_type", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(conversable_type = 'paper' AND conversable_id IS NOT NULL) OR (conversable_type = 'project' AND conversable_id IS NOT NULL) OR (conversable_type = 'everything' AND conversable_id IS NULL)",
            name="check_audio_overview_conversable_consistency",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("conversable_id", sa.UUID(), nullable=True),
        sa.Column("conversable_type", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(conversable_type = 'paper' AND conversable_id IS NOT NULL) OR (conversable_type = 'project' AND conversable_id IS NOT NULL) OR (conversable_type = 'everything' AND conversable_id IS NULL)",
            name="check_conversable_consistency",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "onboarding",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("research_fields", sa.String(), nullable=True),
        sa.Column("research_fields_other", sa.String(), nullable=True),
        sa.Column("job_titles", sa.String(), nullable=True),
        sa.Column("job_titles_other", sa.String(), nullable=True),
        sa.Column("reading_frequency", sa.String(), nullable=True),
        sa.Column("referral_source", sa.String(), nullable=True),
        sa.Column("referral_source_other", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "paper_tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "paper_upload_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("task_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "project",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("admin_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["auth.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "referral_codes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_referral_codes_code"),
        "referral_codes",
        ["code"],
        unique=True,
        schema="scholens",
    )
    op.create_table(
        "referrals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("referrer_user_id", sa.BigInteger(), nullable=False),
        sa.Column("referee_user_id", sa.BigInteger(), nullable=False),
        sa.Column("code_used", sa.String(length=16), nullable=False),
        sa.Column("attribution_method", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("converted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("credit_available_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("referrer_credit_cents", sa.Integer(), nullable=False),
        sa.Column("referee_coupon_id", sa.String(), nullable=True),
        sa.Column("stripe_balance_transaction_id", sa.String(), nullable=True),
        sa.Column("fraud_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "referrer_user_id <> referee_user_id",
            name="check_referral_no_self_referral",
        ),
        sa.ForeignKeyConstraint(
            ["referee_user_id"], ["auth.users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["referrer_user_id"], ["auth.users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("referee_user_id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_referrals_referrer_user_id"),
        "referrals",
        ["referrer_user_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_referrals_status"),
        "referrals",
        ["status"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("plan", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(), nullable=True),
        sa.Column("stripe_price_id", sa.String(), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=True),
        sa.Column("stripe_schedule_id", sa.String(), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        schema="scholens",
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("locale", sa.String(), nullable=True),
        sa.Column(
            "is_admin",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_blocked",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("referral_toast_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        schema="scholens",
    )
    op.create_table(
        "zotero_connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("zotero_user_id", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        schema="scholens",
    )
    op.create_table(
        "zotero_oauth_pending",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("oauth_token", sa.String(), nullable=False),
        sa.Column("oauth_token_secret", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_zotero_oauth_pending_oauth_token"),
        "zotero_oauth_pending",
        ["oauth_token"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "data_table_extraction_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("columns", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("task_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.project.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("references", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trace", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["scholens.conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "papers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("file_url", sa.String(), nullable=False),
        sa.Column("preview_url", sa.String(), nullable=True),
        sa.Column("s3_object_key", sa.String(), nullable=True),
        sa.Column("authors", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("institutions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "summary_citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("publish_date", sa.DateTime(), nullable=True),
        sa.Column("starter_questions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("parser_markdown_s3_key", sa.String(), nullable=True),
        sa.Column("parser_archive_s3_key", sa.String(), nullable=True),
        sa.Column("parser_backend", sa.String(), nullable=True),
        sa.Column("parser_quality", sa.String(), nullable=True),
        sa.Column("parser_version", sa.String(), nullable=True),
        sa.Column("parser_warning_code", sa.String(), nullable=True),
        sa.Column("ts_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column(
            "page_offset_map", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "last_accessed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("upload_job_id", sa.UUID(), nullable=True),
        sa.Column("cached_presigned_url", sa.String(), nullable=True),
        sa.Column(
            "presigned_url_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("share_id", sa.String(), nullable=True),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("journal", sa.String(), nullable=True),
        sa.Column("publisher", sa.String(), nullable=True),
        sa.Column("attempted_metadata_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "field_provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("size_in_kb", sa.Integer(), nullable=True),
        sa.Column("parent_paper_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "parser_backend IS NULL OR parser_backend IN ('mineru', 'pymupdf')",
            name="ck_papers_parser_backend",
        ),
        sa.CheckConstraint(
            "parser_quality IS NULL OR parser_quality IN ('full', 'text_only')",
            name="ck_papers_parser_quality",
        ),
        sa.ForeignKeyConstraint(
            ["parent_paper_id"], ["scholens.papers.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["upload_job_id"], ["scholens.paper_upload_jobs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_papers_share_id"),
        "papers",
        ["share_id"],
        unique=True,
        schema="scholens",
    )
    op.create_index(
        "ix_papers_ts_vector",
        "papers",
        ["ts_vector"],
        unique=False,
        schema="scholens",
        postgresql_using="gin",
    )
    op.create_table(
        "project_audio_overview",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("audio_overview_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["audio_overview_id"], ["scholens.audio_overviews.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.project.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "project_role",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.project.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        "ix_project_role_project_id_user_id",
        "project_role",
        ["project_id", "user_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "project_role_invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("invited_by", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column(
            "invited_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["auth.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.project.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("scope_type", sa.String(), nullable=False),
        sa.Column("scope_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["scholens.messages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        "ix_artifacts_message_id",
        "artifacts",
        ["message_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_artifacts_scope",
        "artifacts",
        ["scope_type", "scope_id", "kind", "created_at"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_artifacts_user_id"),
        "artifacts",
        ["user_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "data_table_extraction_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("columns", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("row_failures", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["scholens.data_table_extraction_jobs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
        schema="scholens",
    )
    op.create_table(
        "highlights",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("position", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("zotero_annotation_key", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.papers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        "uq_highlight_paper_zotero_annotation_key",
        "highlights",
        ["paper_id", "zotero_annotation_key"],
        unique=True,
        schema="scholens",
        postgresql_where=sa.text("zotero_annotation_key IS NOT NULL"),
    )
    op.create_table(
        "paper_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("s3_object_key", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("image_index", sa.Integer(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("placeholder_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.papers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "paper_notes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.papers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paper_id"),
        schema="scholens",
    )
    op.create_table(
        "paper_passages",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("ts_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.papers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paper_id", "start_line"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_paper_passages_paper_id"),
        "paper_passages",
        ["paper_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_paper_passages_ts_vector",
        "paper_passages",
        ["ts_vector"],
        unique=False,
        schema="scholens",
        postgresql_using="gin",
    )
    op.create_table(
        "paper_tag_association",
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.papers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["scholens.paper_tags.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("paper_id", "tag_id"),
        schema="scholens",
    )
    op.create_table(
        "project_paper",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.papers.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scholens.project.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_project_paper_paper_id"),
        "project_paper",
        ["paper_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        op.f("ix_scholens_project_paper_project_id"),
        "project_paper",
        ["project_id"],
        unique=False,
        schema="scholens",
    )
    op.create_table(
        "zotero_imported_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("zotero_item_key", sa.String(), nullable=False),
        sa.Column("zotero_attachment_key", sa.String(), nullable=True),
        sa.Column("import_source", sa.String(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("paper_id", sa.UUID(), nullable=True),
        sa.Column("upload_job_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "annotations_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.papers.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["upload_job_id"], ["scholens.paper_upload_jobs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "zotero_item_key", name="uq_zotero_import_user_item"
        ),
        schema="scholens",
    )
    op.create_table(
        "annotations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("highlight_id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["highlight_id"],
            ["scholens.highlights.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.papers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_table(
        "data_table_rows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("data_table_id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["data_table_id"],
            ["scholens.data_table_extraction_results.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["scholens.papers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="scholens",
    )
    op.create_index(
        "ix_data_table_rows_data_table_id",
        "data_table_rows",
        ["data_table_id"],
        unique=False,
        schema="scholens",
    )
    op.create_index(
        "ix_data_table_rows_paper_id",
        "data_table_rows",
        ["paper_id"],
        unique=False,
        schema="scholens",
    )
    op.execute(
        """
        CREATE FUNCTION scholens.paper_content_trigger() RETURNS trigger AS $$
        BEGIN
            NEW.ts_vector :=
                setweight(
                    to_tsvector('pg_catalog.english', coalesce(NEW.title, '')),
                    'A'
                ) ||
                setweight(
                    to_tsvector('pg_catalog.english', coalesce(NEW.raw_content, '')),
                    'D'
                );
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER tsvectorupdate
            BEFORE INSERT OR UPDATE ON scholens.papers
            FOR EACH ROW
            EXECUTE FUNCTION scholens.paper_content_trigger()
        """
    )
    op.execute(
        """
        CREATE FUNCTION scholens.paper_passages_tsvector_trigger()
        RETURNS trigger AS $$
        BEGIN
            NEW.ts_vector :=
                to_tsvector('pg_catalog.english', coalesce(NEW.content, ''));
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER paper_passages_tsvectorupdate
            BEFORE INSERT OR UPDATE ON scholens.paper_passages
            FOR EACH ROW
            EXECUTE FUNCTION scholens.paper_passages_tsvector_trigger()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_token_usage_user_week",
        table_name="token_usage_events",
        schema="scholens",
    )
    op.drop_table("token_usage_events", schema="scholens")
    op.drop_table("token_weekly_usage", schema="scholens")
    op.drop_table("stripe_webhook_events", schema="scholens")
    op.drop_table("jobs_webhook_nonces", schema="scholens")
    op.execute(
        "DROP TRIGGER IF EXISTS paper_passages_tsvectorupdate "
        "ON scholens.paper_passages"
    )
    op.execute("DROP FUNCTION IF EXISTS scholens.paper_passages_tsvector_trigger()")
    op.execute("DROP TRIGGER IF EXISTS tsvectorupdate ON scholens.papers")
    op.execute("DROP FUNCTION IF EXISTS scholens.paper_content_trigger()")
    op.drop_index(
        "ix_data_table_rows_paper_id", table_name="data_table_rows", schema="scholens"
    )
    op.drop_index(
        "ix_data_table_rows_data_table_id",
        table_name="data_table_rows",
        schema="scholens",
    )
    op.drop_table("data_table_rows", schema="scholens")
    op.drop_table("annotations", schema="scholens")
    op.drop_table("zotero_imported_items", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_project_paper_project_id"),
        table_name="project_paper",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_project_paper_paper_id"),
        table_name="project_paper",
        schema="scholens",
    )
    op.drop_table("project_paper", schema="scholens")
    op.drop_table("paper_tag_association", schema="scholens")
    op.drop_index(
        "ix_paper_passages_ts_vector",
        table_name="paper_passages",
        schema="scholens",
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_scholens_paper_passages_paper_id"),
        table_name="paper_passages",
        schema="scholens",
    )
    op.drop_table("paper_passages", schema="scholens")
    op.drop_table("paper_notes", schema="scholens")
    op.drop_table("paper_images", schema="scholens")
    op.drop_index(
        "uq_highlight_paper_zotero_annotation_key",
        table_name="highlights",
        schema="scholens",
        postgresql_where=sa.text("zotero_annotation_key IS NOT NULL"),
    )
    op.drop_table("highlights", schema="scholens")
    op.drop_table("data_table_extraction_results", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_artifacts_user_id"),
        table_name="artifacts",
        schema="scholens",
    )
    op.drop_index("ix_artifacts_scope", table_name="artifacts", schema="scholens")
    op.drop_index("ix_artifacts_message_id", table_name="artifacts", schema="scholens")
    op.drop_table("artifacts", schema="scholens")
    op.drop_table("project_role_invitations", schema="scholens")
    op.drop_index(
        "ix_project_role_project_id_user_id",
        table_name="project_role",
        schema="scholens",
    )
    op.drop_table("project_role", schema="scholens")
    op.drop_table("project_audio_overview", schema="scholens")
    op.drop_index(
        "ix_papers_ts_vector",
        table_name="papers",
        schema="scholens",
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_scholens_papers_share_id"), table_name="papers", schema="scholens"
    )
    op.drop_table("papers", schema="scholens")
    op.drop_table("messages", schema="scholens")
    op.drop_table("data_table_extraction_jobs", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_zotero_oauth_pending_oauth_token"),
        table_name="zotero_oauth_pending",
        schema="scholens",
    )
    op.drop_table("zotero_oauth_pending", schema="scholens")
    op.drop_table("zotero_connections", schema="scholens")
    op.drop_table("user_profiles", schema="scholens")
    op.drop_table("subscriptions", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_referrals_status"),
        table_name="referrals",
        schema="scholens",
    )
    op.drop_index(
        op.f("ix_scholens_referrals_referrer_user_id"),
        table_name="referrals",
        schema="scholens",
    )
    op.drop_table("referrals", schema="scholens")
    op.drop_index(
        op.f("ix_scholens_referral_codes_code"),
        table_name="referral_codes",
        schema="scholens",
    )
    op.drop_table("referral_codes", schema="scholens")
    op.drop_table("project", schema="scholens")
    op.drop_table("paper_upload_jobs", schema="scholens")
    op.drop_table("paper_tags", schema="scholens")
    op.drop_table("onboarding", schema="scholens")
    op.drop_table("conversations", schema="scholens")
    op.drop_table("audio_overviews", schema="scholens")
    op.drop_table("audio_overview_jobs", schema="scholens")
    # ### end Alembic commands ###
